### ISSUE TITLE
fix: clean-up annotations

### ISSUE THREAD

**Issue by edkerk** [SysBioChalmers/Sco-GEM#105]
### Description of the issue:
Some overlap with #33 and #44, but bigger scope here. If this issue is settled, then the other two can also be closed.

Various (minor) issues exist with current annotations of genes, mets and rxns:
- [x] 1. `metanetx` is sometimes misspelled as `metabetx`
- [x] 2. About 21 metabolites are annotated to `3dmet`. Either annotate all metabolites (as far as possible) to this database, or drop the annotation of these few metabolites. This is not a [database](http://www.3dmet.dna.affrc.go.jp/met_index.php) commonly used for GEMs, the model is not using 3D structures of metabolites, so drop the annotation.
- [x] 3. About 19 metabolites are annotated to `cas`. Either annotate all metabolites (as far as possible) to this database, or drop the annotation of these few metabolites. This is not a [database](https://www.cas.org/support/documentation/chemical-substances) commonly used for GEMs, so drop the annotation.
- [x] 4. About 27 metabolites are annotated to `pubchem.substance`. The more common database is `pubchem.compound`. Drop the `pubchem.substance` annotation and make sure that the `pubchem.compound` is included for those metabolites.
- [x] 5. Only N-Acetyl-L-Cysteine is annotated to `kegg.drugs`, while `kegg.compound` is also defined. Drop the `kegg.drugs` annotation.
- [x] 6. Some ChEBI annotations are misrepresented, as `CHEBI%3A15377` instead of `CHEBI:15377`. Each of the metabolites is also annotated with the correct ChEBI annotation: remove the incorrect ones.

- [x] 7. About 17 reactions are annotated to `kegg.ontology`. This is mostly redundant to the more commonly used `kegg.reactions`, which are annotated to 1369 reactions (including the 17 reactiosn with `kegg.ontology`). Drop the annotation.

- [ ] ~~8. Of the 1778 genes, 215 are annotated with GO terms. Should this be extended to all genes, or should `go` as annotation be dropped?~~ See #44
- [ ] ~~9. Of the 1778 genes, 219 are annotated with PFAM domains. Should this be extended to all genes, or should `pfam` as annotation be dropped?~~ See #44

#### Expected feature/value/output:

- Do not include sporious annotations to databases that are not commonly used:
  - Either remove the uncommon database, ...
  - ... or increase the coverage to all members.
- Improve coverage of common annotations (e.g. SEED, currently covering 1.9% of metabolites), will be handled in a separate issue.

#### To do:
If agreed to remove the sporious annotations to uncommon databases, to do list will be included here.

**I hereby confirm that:**
- [x] This problem persists in the `master` branch of the repository
- [x] A similar issue does not already exist
- [x] I've considered asking this first in the [Gitter chat room](https://gitter.im/SysBioChalmers/sco-GEM)

**Comment by edkerk** [comment]
Additional realisation: what is currently in the BioCyc field are actually MetaCyc identifiers. E.g. [memote](https://github.com/opencobra/memote/) (see example report [here](https://sysbiochalmers.github.io/Sco-GEM/snapshot.html)) checks for BioCyc identifiers. To turn MetaCyc identifiers into BioCyc identifiers they have to be prefixed with `META:`:

- `META:F16ALDOLASE-RXN` instead of `F16ALDOLASE-RXN`

These identifiers are then also following specifications on [Identifiers.org](https://registry.identifiers.org/registry/biocyc).

 - [ ] Correct BioCyc identifiers by adding `META:` prefix.

**Comment by sulheim** [comment]
- [ ] Fix annotations issues raised by @smoretti in #111

**Comment by edkerk** [comment]
The GO term and PFAM annotations to the genes will first be discarded, as these are assigned inconsistently (only about 200 of 1778 genes have these annotations). Meanwhile #44 remains open, where additional gene annotations are proposed.

**Comment by sulheim** [comment]
These annotations are already in this repository under [data/sulheim2020/annotations/genes.csv](https://github.com/SysBioChalmers/Sco-GEM/blob/devel/data/sulheim2020/annotations/genes.csv). We can add GO and PFAM annotations from this spreadsheet into the model file.

**Comment by edkerk** [comment]
Ah, we already have that data, great. This will then be done in #44 and not addressed here.
