### ISSUE TITLE
fix: ids and annotation bugs

### ISSUE THREAD

**Issue by sulheim** [SysBioChalmers/Sco-GEM#33]
### Description of the issue:
I have discovered a couple of bugs in the annotation /ids of the metabolites including:
- "_c or _e" appended to BiGG annotations (e.g bigg.metabolite: actACPmmy_c)
- "_c" appended to biocyc annotations (e.g biocyc: CPD-209_c)
- metabolite malonyl-mmyA has id: *temp*. Should be malACPmmy_c
- metabolite with name acetoacetyl-mmyA has id: *malACPmmy_c*.  Should be *actACPmmy_c*
- empty annotations (i.e kegg.compound: '')
- Some biocyc annotations has *NADH* or *NADPH* appended
- Metabolite 44dpcopd_c should have KEGG ID C21770
- Correct reaction ID PSEDUO_ACCEPTOR_NADP

#### Tasks
- [x] Remove "_c or _e" from all BiGG  annotations
- [x] Remove "_c" from all biocyc  annotations
- [x] Fix ids of metabolites malACPmmy_c and temp
- [x] Remove empty annotations
- [x] Remove appended NADH or NADPH from biocyc annotations
- [x] Give metabolite 44dpcopd_c KEGG ID C21770
- [x] Correct reaction ID PSEDUO_ACCEPTOR_NADP

**Comment by sulheim** [comment]
98 reactions have _META:_ in the beginning of the BioCyc annotation, e.g. the biocyc-annotation of the reaction ASPabc is now _META:TRANS-RXN0-222_ but should be _TRANS-RXN0-222_. An additional bug is that the reaction ZCAROTDH2 has completely wrong biocyc annotation.
- [ ] remove _META:_ from all biocyc annotations (98 reactions)
- [ ] correct annotation for the reaction ZCAROTDH2

**Comment by edkerk** [comment]
Let's not reuse this issue to report new minor bugs but make separate issues, to avoid confusion when refering to issues in PRs.
